name: "sast-scan"

on:
  push:
    branches: [githubcicd]

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --force

      - name: Download OWASP Dependency-Check
        run: |
          wget 
https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.1/dependency-check-12.1.1-release.zip
          unzip -q dependency-check-12.1.1-release.zip -d 
$HOME/dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          chmod +x 
$HOME/dependency-check/dependency-check/bin/dependency-check.sh
          $HOME/dependency-check/dependency-check/bin/dependency-check.sh 
\
            --project "bitcoin" \
            --nvdApiKey ${{ secrets.WORKSHOP6_NVD_API_KEY }} \
            --out . \
            --scan . \
            --disableOssIndex

      - name: Archive SAST report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: ./dependency-check-report.html

